import pandas as pd

class ScoutConcepts():
    def __init__(self):
        self.scenarios = ["Max adoption potential", "Technical adoption potential"]

        self.ecms = [
                '90.1 Com. N-Elec. Env.',
                'Best Com. ASHP, Env., PC (EE+DF–FS)',
                'Best Com. ASHP, Env., PC (EE+DF–FS) CC',
                'Best Com. ASHP, Env., PC (EE+DF–LFL)',
                'Best Com. ASHP, Env., PC (EE+DF–LFL) CC',
                'Best Com. ASHP, Env., PC (EE+DF–RST)',
                'Best Com. ASHP, Env., PC (EE+DF–RST) CC',
                'Best Com. Chillers, Env., PC (EE+DF)',
                'Best Com. Chillers, Ice (EE+DF)',
                'Best Com. Lighting (EE+DF)',
                'Best Com. N-Elec. Env.',
                'Best Com. Plug Loads (EE+DF)',
                'Best Com. RTU, Env., PC (EE+DF)',
                'Best Commercial Gas Storage WH',
                'Best Commercial HPWH',
                'Best Commercial HPWH (FS)',
                'Best Commercial Refrigeration',
                'Best Res. ASHP, Env., PC (EE+DF–FS)',
                'Best Res. ASHP, Env., PC (EE+DF–FS) CC',
                'Best Res. ASHP, Env., PC (EE+DF–LFL)',
                'Best Res. ASHP, Env., PC (EE+DF–LFL) CC',
                'Best Res. ASHP, Env., PC (EE+DF–RST)',
                'Best Res. ASHP, Env., PC (EE+DF–RST) CC',
                'Best Res. CAC, Env., PC (EE+DF)',
                'Best Res. Clothes Dryer (EE+DF)',
                'Best Res. Clothes Washer (EE+DF)',
                'Best Res. Dishwasher (EE+DF)',
                'Best Res. Electronics (EE+DF)',
                'Best Res. HPWH (EE+DF)',
                'Best Res. HPWH (EE+DF–FS)',
                'Best Res. N-Elec. Env.',
                'Best Res. Pool Pump (EE+DF)',
                'Best Residential Gas Dryer',
                'Best Residential Gas Storage WH',
                'Best Residential LED Lighting',
                'Best Residential Oil WH',
                'Best Residential Refrigerator',
                'Com. Cooking (FS)',
                'Com. Fossil Heating, Ref. Case',
                'Com. Fossil Heating, Ref. Case (2030)',
                'Com. Fossil Heating, Ref. Case (2035)',
                'Commercial Lighting, 90.1 c. 2019',
                'Commercial Lighting, Ref. Case',
                'Commercial Plug Loads, Tier 1 APS',
                'ENERGY STAR Com. ASHP (FS) + Env.',
                'ENERGY STAR Com. ASHP (FS) + Env. CC',
                'ENERGY STAR Com. ASHP (LFL) + Env.',
                'ENERGY STAR Com. ASHP (LFL) + Env. CC',
                'ENERGY STAR Com. ASHP (RST) + Env.',
                'ENERGY STAR Com. ASHP (RST) + Env. CC',
                'ENERGY STAR Com. RTU + Env.',
                'ENERGY STAR Commercial Gas WH v. 2.0',
                'ENERGY STAR Electric Dryers',
                'ENERGY STAR Electronics',
                'ENERGY STAR Gas Dryers v. 1.1',
                'ENERGY STAR Gas Storage WH v. 4.0',
                'ENERGY STAR Refrigerator',
                'ENERGY STAR Res. ASHP (FS) + Env.',
                'ENERGY STAR Res. ASHP (FS) + Env. CC',
                'ENERGY STAR Res. ASHP (LFL) + Env.',
                'ENERGY STAR Res. ASHP (LFL) + Env. CC',
                'ENERGY STAR Res. ASHP (RST) + Env.',
                'ENERGY STAR Res. ASHP (RST) + Env. CC',
                'ENERGY STAR Res. CAC + Env.',
                'ENERGY STAR Res. HPWH',
                'ENERGY STAR Res. HPWH (FS)',
                'ESTAR IECC Res. N-Elec. Env.',
                'Prosp. Com. ASHP (FS) + Env. + Ctls.',
                'Prosp. Com. ASHP (FS) + Env. + Ctls. CC',
                'Prosp. Com. ASHP (LFL) + Env. + Ctls.',
                'Prosp. Com. ASHP (LFL) + Env. + Ctls. CC',
                'Prosp. Com. ASHP (RST) + Env. + Ctls.',
                'Prosp. Com. ASHP (RST) + Env. + Ctls. CC',
                'Prosp. Com. Chillers + Env. + Ctls.',
                'Prosp. Com. N-Elec. Env.',
                'Prosp. Com. N-Elec. Env. + Ctls.',
                'Prosp. Com. RTU + Env. + Ctls.',
                'Prosp. Res. ASHP (FS) + Env. + Ctls.',
                'Prosp. Res. ASHP (FS) + Env. + Ctls. CC',
                'Prosp. Res. ASHP (LFL) + Env. + Ctls.',
                'Prosp. Res. ASHP (LFL) + Env. + Ctls. CC',
                'Prosp. Res. ASHP (RST) + Env. + Ctls.',
                'Prosp. Res. ASHP (RST) + Env. + Ctls. CC',
                'Prosp. Res. CAC + Env. + Ctls.',
                'Prosp. Res. N-Elec. Env.',
                'Prosp. Res. N-Elec. Env. + Ctls.',
                'Prospective Com. Ctls. (Lighting)',
                'Prospective Commercial HPWH',
                'Prospective Commercial HPWH (FS)',
                'Prospective Commercial Refrigeration',
                'Prospective Residential Ctls. (Lighting)',
                'Prospective Residential Dryer',
                'Prospective Residential HPWH',
                'Prospective Residential HPWH (FS)',
                'Prospective Residential Refrigeration',
                'Ref. Case Clothes Washer',
                'Ref. Case Com. ASHP (FS)',
                'Ref. Case Com. ASHP (FS) CC',
                'Ref. Case Com. ASHP (LFL)',
                'Ref. Case Com. ASHP (LFL) CC',
                'Ref. Case Com. ASHP (RST)',
                'Ref. Case Com. ASHP (RST) CC',
                'Ref. Case Com. Chillers',
                'Ref. Case Com. Elec. HVAC (FS)',
                'Ref. Case Com. Elec. HVAC (FS) CC',
                'Ref. Case Com. Elec. WH (FS)',
                'Ref. Case Com. Plug Loads',
                'Ref. Case Com. RTU',
                'Ref. Case Com. Refrigeration',
                'Ref. Case Commercial Gas WH v. 2.0',
                'Ref. Case Electric Dryers',
                'Ref. Case Electronics',
                'Ref. Case Gas Dryers v. 1.1',
                'Ref. Case Gas Storage WH v. 4.0',
                'Ref. Case LED Bulbs',
                'Ref. Case Other Res. Heating (FS)',
                'Ref. Case Other Res. Heating (FS) CC',
                'Ref. Case Refrigerator',
                'Ref. Case Res. ASHP (FS)',
                'Ref. Case Res. ASHP (FS) CC',
                'Ref. Case Res. ASHP (LFL)',
                'Ref. Case Res. ASHP (LFL) CC',
                'Ref. Case Res. ASHP (RST)',
                'Ref. Case Res. ASHP (RST) CC',
                'Ref. Case Res. CAC',
                'Ref. Case Res. Dishwasher',
                'Ref. Case Res. Elec. HVAC (FS)',
                'Ref. Case Res. Elec. HVAC (FS) CC',
                'Ref. Case Res. Elec. WH (FS)',
                'Ref. Case Res. HPWH',
                'Ref. Case Res. Pool Pump',
                'Res. Cooking (FS)',
                'Res. Fossil Heating, Ref. Case',
                'Res. Fossil Heating, Ref. Case (2030)',
                'Res. Fossil Heating, Ref. Case (2035)',
                'Residential Oil WH, 90.1 c. 2019',
                'Residential Oil WH, Ref. Case'
                ]

        self.regions = [
                'AIA_CZ1', 'AIA_CZ2', 'AIA_CZ3', 'AIA_CZ4', 'AIA_CZ5',
                'NYUP', 'CASO', 'PJMC', 'CANO', 'PJMD', 'RMRG', 'NYCW', 'MISE', 'MISC',
                'PJMW', 'PJME', 'SRSG', 'NWPP', 'ISNE', 'MISW', 'TRE', 'SPPN', 'SPPC',
                'SPPS', 'MISS', 'SRCE', 'FRCC', 'SRSE', 'SRCA', 'BASN',
                'WA', 'AK', 'RI', 'OK', 'AR', 'NH', 'WI', 'WY', 'IA', 'MS', 'MI', 'CA',
                'MN', 'NE', 'OH', 'NV', 'NY', 'FL', 'NM', 'CO', 'SD', 'MD', 'VA', 'SC',
                'NJ', 'MT', 'ME', 'MA', 'NC', 'OR', 'UT', 'HI', 'KS', 'CT', 'TN', 'ID',
                'ND', 'VT', 'WV', 'GA', 'LA', 'PA', 'DE', 'TX', 'AZ', 'MO', 'IL', 'DC',
                'AL', 'KY', 'IN'
                ]

        self.building_types = [
                'Retail', 'Assembly/Other', 'Warehouses', 'Multi Family Homes',
                'Education', 'Large Offices', 'Single Family Homes',
                'Small/Medium Offices', 'Hospitality', 'Hospitals',
                'single family home',
                'multi family home',
                'mobile home',
                'assembly',
                'education',
                'food sales',
                'food service',
                'health care',
                'lodging',
                'large office',
                'small office',
                'mercantile/service',
                'warehouse',
                'other',
                'unspecified'
                ]

        self.fuel_types = [
                'electricity', 'Electric',
                'natural gas', 'Natural Gas',
                'Propane', 'propane',
                'distillate', 'Distillate/Other', 'Biomass',
                'other fuel'
                ]

        self.end_uses = [
                'Water Heating',
                'Other',
                'Cooking',
                'Refrigeration',
                'Ventilation',
                'Heating (Equip.)',
                'Cooling (Equip.)',
                'Computers and Electronics',
                'Lighting',
                'heating',
                'cooling',
                'lighting',
                'MELs',
                'refrigeration',
                'other',
                'secondary heating',
                'water heating',
                'cooking',
                'ventilation',
                'TVs',
                'computers',
                'onsite generation',
                'drying',
                'PCs',
                'non-PC office equipment',
                'ceiling fan',
                'fans and pumps',
                'unspecified'
                ]

        self.supply_demand = ['supply', 'demand']
        self.energy_stock = ['energy', 'stock']

        self.technologies = [
                '100W Equivalent A19 Halogen',
                '100W Equivalent CFL Bare Spiral',
                '100W A19 Incandescent',
                'ASHP',
                'CAV_Vent',
                'Commercial Beverage Merchandisers',
                'Commercial Ice Machines',
                'Commercial Reach-In Freezers',
                'Commercial Reach-In Refrigerators',
                'Commercial Refrigerated Vending Machines',
                'Commercial Supermarket Display Cases',
                'Commercial Walk-In Freezers',
                'Commercial Walk-In Refrigerators',
                'GSHP',
                'Halogen Infrared Reflector (HIR) PAR38',
                'Halogen PAR38',
                'HP water heater',
                'IT equipment',
                'LED Integrated Luminaire',
                'LED PAR38',
                'Metal Halide',
                'Mercury Vapor',
                'NGHP',
                'OTT streaming devices',
                'Sodium Vapor',
                'Solar water heater',
                'T5 4xF54 HO High Bay',
                'T5 F28',
                'T8 F28',
                'T8 F32',
                'T8 F59',
                'T8 F96',
                'TV',
                'VAV_Vent',
                'boiler (NG)',
                'boiler (distillate)',
                'central AC',
                'centrifugal_chiller',
                'clothes washing',
                'coffee brewers',
                'coffee maker',
                'comm_GSHP-cool',
                'comm_GSHP-heat',
                'data center UPS',
                'dehumidifier',
                'desktop PC',
                'dishwasher',
                'distribution transformers',
                'elec_boiler',
                'elec_water_heater',
                'electric WH',
                'electric other',
                'electric_range_oven_24x24_griddle',
                'electric_res-heat',
                'elevators',
                'equipment gain',
                'escalators',
                'external (CFL)',
                'external (LED)',
                'external (high pressure sodium)',
                'external (incandescent)',
                'floor',
                'freezers',
                'fume hoods',
                'furnace (LPG)',
                'furnace (NG)',
                'furnace (distillate)',
                'gas_boiler',
                'gas_chiller',
                'gas_eng-driven_RTAC',
                'gas_eng-driven_RTHP-cool',
                'gas_eng-driven_RTHP-heat',
                'gas_furnace',
                'gas_range_oven_24x24_griddle',
                'gas_water_heater',
                'general service (CFL)',
                'general service (LED)',
                'general service (incandescent)',
                'ground',
                'home theater and audio',
                'infiltration',
                'kitchen ventilation',
                'lab fridges and freezers',
                'laptop PC',
                'large video boards',
                'laundry',
                'lighting gain',
                'linear fluorescent (LED)',
                'linear fluorescent (T-8)',
                'linear fluorescent (T-12)',
                'medical imaging',
                'microwave',
                'monitors',
                'network equipment',
                'non-road electric vehicles',
                'office UPS',
                'oil_boiler',
                'oil_furnace',
                'oil_water_heater',
                'other',
                'other appliances',
                'other heat gain',
                'people gain',
                'private branch exchanges',
                'pool heaters',
                'pool pumps',
                'portable electric spas',
                'reciprocating_chiller',
                'rechargeables',
                'reflector (CFL)',
                'reflector (LED)',
                'reflector (halogen)',
                'reflector (incandescent)',
                'res_type_central_AC',
                'res_type_gasHP-cool',
                'res_type_gasHP-heat',
                'resistance',
                'resistance heat',
                'roof',
                'rooftop_AC',
                'rooftop_ASHP-cool',
                'rooftop_ASHP-heat',
                'room AC',
                'set top box',
                'screw_chiller',
                'scroll_chiller',
                'security system',
                'security systems',
                'secondary heater',
                'secondary heater (LPG)',
                'secondary heater (coal)',
                'secondary heater (kerosene)',
                'secondary heater (wood)',
                'shredders',
                'small kitchen appliances',
                'smart speakers',
                'smartphones',
                'solar WH',
                'stove (wood)',
                'tablets',
                'telecom systems',
                'ventilation',
                'video game consoles',
                'voice-over-IP telecom',
                'wall',
                'wall-window_room_AC',
                'water services',
                'windows conduction',
                'windows solar',
                'wine coolers'
            ]

        self.outcome_metrics = [
                'Avoided CO\u2082 Emissions (MMTons)', #'Avoided CO₂ Emissions (MMTons)',
                'Baseline CO\u2082 Cost (USD)', #'Baseline CO₂ Cost (USD)',
                'Baseline CO\u2082 Emissions (MMTons)', #'Baseline CO₂ Emissions (MMTons)',
                'Baseline Energy Use (MMBtu)',
                'Baseline Energy Cost (USD)',
                'CO\u2082 Cost Savings (USD)', #'CO₂ Cost Savings (USD)',
                'CO\u2082 Emissions (MMTons)', # CO₂ Emissions (MMTons)
                'Cost of Conserved CO\u2082 ($/MTon CO\u2082 avoided)', #'Cost of Conserved CO₂ ($/MTon CO₂ avoided)'
                'Cost of Conserved Energy ($/MMBtu saved)',
                'Efficient CO\u2082 Cost (USD)', #'Efficient CO₂ Cost (USD)',
                'Efficient CO\u2082 Emissions (MMTons)', #'Efficient CO₂ Emissions (MMTons)',
                'Efficient Energy Cost (USD)',
                'Efficient Energy Use (MMBtu)',
                'Energy (MMBtu)',
                'Energy Cost (USD)',
                'Energy Cost Savings (USD)',
                'Energy Savings (MMBtu)',
                'IRR (%)',
                'Payback (years)'
                ]

        self.years = [str(x) for x in range(2000, 2100)]

        self.defined_values = (
                self.ecms + self.scenarios +
                self.regions + self.building_types + self.fuel_types + self.end_uses +
                self.supply_demand + self.energy_stock + self.technologies + self.years
                )

class ScoutMappings():
    def __init__(self):
        self.building_classes = pd.DataFrame(
                [
                    {
                        'building_class0': 'Commercial (New)',
                        'structure_type': 'New',
                        'building_class': 'Commercial'
                     },
                    {
                        'building_class0': 'Commercial (Existing)',
                        'structure_type': 'Existing',
                        'building_class': 'Commercial'
                     },
                    {
                        'building_class0': 'Residential (New)',
                        'structure_type': 'New',
                        'building_class': 'Residential'
                     },
                    {
                        'building_class0': 'Residential (Existing)',
                        'structure_type': 'Existing',
                        'building_class': 'Residential'
                     }
                ]
                )

        self.building_type_class = pd.DataFrame(
                [
                    {'building_type' : 'Assembly/Other',      'building_class': 'Commercial'},
                    {'building_type': 'Education',            'building_class': 'Commercial'},
                    {'building_type': 'Hospitality',          'building_class': 'Commercial'},
                    {'building_type': 'Hospitals',            'building_class': 'Commercial'},
                    {'building_type': 'Large Offices',        'building_class': 'Commercial'},
                    {'building_type': 'Multi Family Homes',   'building_class': 'Residential'},
                    {'building_type': 'Retail',               'building_class': 'Commercial'},
                    {'building_type': 'Single Family Homes',  'building_class': 'Residential'},
                    {'building_type': 'Small/Medium Offices', 'building_class': 'Commercial'},
                    {'building_type': 'Warehouse',            'building_class': 'Commercial'},
                    {'building_type': 'assembly',           'building_class': 'Commercial'},
                    {'building_type': 'education',          'building_class': 'Commercial'},
                    {'building_type': 'food sales',         'building_class': 'Commercial'},
                    {'building_type': 'food service',       'building_class': 'Commercial'},
                    {'building_type': 'health care',        'building_class': 'Commercial'},
                    {'building_type': 'lodging',            'building_class': 'Commercial'},
                    {'building_type': 'large office',       'building_class': 'Commercial'},
                    {'building_type': 'small office',       'building_class': 'Commercial'},
                    {'building_type': 'mercantile/service', 'building_class': 'Commercial'},
                    {'building_type': 'warehouse',          'building_class': 'Commercial'},
                    {'building_type': 'other',              'building_class': 'Commercial'},
                    {'building_type': 'unspecified',        'building_class': 'Commercial'},
                    {'building_type': 'single family home', 'building_class': 'Residential'},
                    {'building_type': 'multi family home',  'building_class': 'Residential'},
                    {'building_type': 'mobile home',        'building_class': 'Residential'},
                    {'building_type': 'Mobile Homes',       'building_class': 'Residential'}
                ])

